extends Node

enum Alignment { RADIANT, VILE, PRIMAL }
enum Rarity { COMMON, UNCOMMON, RARE, EPIC, LEGENDARY }
enum CardType { ATTACK, DEFENSE, SUPPORT, SPECIAL }
enum MasteryTier { UNMASTERED, BRONZE, SILVER, GOLD, EVOLVED }
enum TargetType { SINGLE_ENEMY, ALL_ENEMIES, SELF, SINGLE_ALLY, ALL_ALLIES }
enum GrimoireCover { LEATHER, BONE, CRYSTAL, CLOTH, METAL }
enum GrimoireBinding { CHAIN, RIBBON, VINE, CLASP, RUNE_THREAD }

# --- Phase 2: Battle System ---
enum EffectType { DAMAGE, HEAL, BLOCK, POISON, BURN, DRAW, MANA_GAIN, BUFF_ATTACK, DEBUFF_ATTACK }
enum StatusType { POISON, BURN, WEAKNESS, STRENGTH, SHIELD, REGEN }
enum ConditionType { NONE, IF_ALIGNMENT_MATCH, IF_HP_BELOW_HALF, IF_FIRST_PLAY }
enum EnemyIntent { ATTACK, DEFEND, BUFF, DEBUFF, SPECIAL }
enum BattleState { NOT_STARTED, PLAYER_TURN, ENEMY_TURN, VICTORY, DEFEAT }

# --- Phase 3: PvE Campaign ---
enum NodeType { COMBAT, MORAL_CHOICE, TREASURE, REST, BOSS }
enum ChapterTheme { FORGOTTEN_LIBRARY, BURNING_ARCHIVE, OVERGROWN_SCRIPTORIUM }
